$(document).ready(function(){	
	/*购物车*/
	$(".dl").mousemove(function(){
		$(".span").css({
			"display":"block",
		});
		$(".dl").css({
			"border":"1px solid #000",
			"border-bottom":"none",
			"background-color":"#fff",
		});
	});	
	$(".dl").mouseleave(function(){
		$(".span").css({
			"display":"none",
		});
		$(".dl").css({
			"border":"1px solid #fff",
		});
	});	
	$(".span").mousemove(function(){
		$(".span").css({
			"display":"block",
		});
		$(".dl").css({
			"border":"1px solid #000",
			"border-bottom":"none",
		});
	});
	$(".span").mouseleave(function(){
		$(".span").css({
			"display":"none",
		});
		$(".dl").css({
			"border":"1px solid #fff",
		});
	});
	/*搜索框*/
	$("#png").click(function(){
		$("#png").css({
			"display":"none",
		});
		$("#input").show(500);
		$("#p1").animate({
			"top":"-16px",
			"left":"10px",
		},600);
		$("#p2").animate({
			"top":"-16px",
			"left":"10px",
		},600);
		$("#p3").css({
			"display":"block",
		});
	});	
	$("#p3").click(function(){
		$("#png").css({
			"display":"block",
		});
		$("#input").delay(500).hide(500);
		$("#p1").animate({
			"top":"20px",
			"left":"20px",
		},500);
		
		$("#p2").animate({
			"top":"-60px",
			"left":"20px",
		},500);
		
		$("#png").show(8000);
	});
	/*导航条 navigate*/
	$(".a").mousemove(function(){
		$("#span1").show();
	});
	$(".a").mouseleave(function(){
		$("#span1").hide();
	});
	$(".b").mousemove(function(){
		$("#span2").show();
	});
	$(".b").mouseleave(function(){
		$("#span2").hide();
	});
	$(".c").mousemove(function(){
		$("#span3").show();
	});
	$(".c").mouseleave(function(){
		$("#span3").hide();
	});
	$(".d").mousemove(function(){
		$("#span4").show();
	});
	$(".d").mouseleave(function(){
		$("#span4").hide();
	});
	$("#span1").mousemove(function(){
		$("#span1").show();
	});
	$("#span1").mouseleave(function(){
		$("#span1").hide();
	});
	$("#span2").mousemove(function(){
		$("#span2").show();
	});
	$("#span2").mouseleave(function(){
		$("#span2").hide();
	});
	$("#span3").mousemove(function(){
		$("#span3").show();
	});
	$("#span3").mouseleave(function(){
		$("#span3").hide();
	});
	$("#span4").mousemove(function(){
		$("#span4").show();
	});
	$("#span4").mouseleave(function(){
		$("#span4").hide();
	});
	$(".new").mouseover(function(){
		$("#span5").show();
	});
	$(".new").mouseleave(function(){
		$("#span5").hide();
	});
	$("#span5").mouseover(function(){
		$("#span5").show();
	});
	$("#span5").mouseleave(function(){
		$("#span5").hide();
	});
	$(".nts").mouseover(function(){
		$("#span6").show();
	});
	$(".nts").mouseleave(function(){
		$("#span6").hide();
	});
	$("#span6").mouseover(function(){
		$("#span6").show();
	});
	$("#span6").mouseleave(function(){
		$("#span6").hide();
	});
	$(".newon").mouseover(function(){
		$("#span7").show();
	});
	$(".newon").mouseleave(function(){
		$("#span7").hide();
	});
	$("#span7").mouseover(function(){
		$("#span7").show();
	});
	$("#span7").mouseleave(function(){
		$("#span7").hide();
	});
	$(".sweet").mouseover(function(){
		$("#span8").show();
	});
	$(".sweet").mouseleave(function(){
		$("#span8").hide();
	});
	$("#span8").mouseover(function(){
		$("#span8").show();
	});
	$("#span8").mouseleave(function(){
		$("#span8").hide();
	});
	/*banner图片遮罩层*/
	$("#play").mouseover(function(){
		$(".play1").animate({
			"opacity":0.3,
		});
	});
	$("#play").mouseleave(function(){
		$(".play1").animate({
			"opacity":0,
		});
	});
	$("#play2").mouseover(function(){
		$(".play3").animate({
			"opacity":0.3,
		});
	});
	$("#play2").mouseleave(function(){
		$(".play3").animate({
			"opacity":0,
		});
	});
	$(".three").mouseover(function(){
		$(".span3").animate({
			"opacity":0.3,
		});
		$(".f").animate({
			"left":"45px",
		},500);
	});
	$(".three").mouseleave(function(){
		$(".span3").animate({
			"opacity":0,
		});
		$(".f").animate({
			"left":"-200px",
		},200);
	});	
	/*banner one 部分*/
	$(".right_1").mouseover(function(){
		$("#shop").animate({
			"opacity":0.3,
		});
	});
	$(".right_1").mouseleave(function(){
		$("#shop").animate({
			"opacity":0,
		});
	});
	$(".right_2").mouseover(function(){
		$("#shop2").animate({
			"opacity":0.3,
		});
	});
	$(".right_2").mouseleave(function(){
		$("#shop2").animate({
			"opacity":0,
		});
	});
	$(".right_3").mouseover(function(){
		$("#shop3").animate({
			"opacity":0.3,
		});
	});
	$(".right_3").mouseleave(function(){
		$("#shop3").animate({
			"opacity":0,
		});
	});
	$(".right_4").mouseover(function(){
		$("#shop4").animate({
			"opacity":0.3,
		});
	});
	$(".right_4").mouseleave(function(){
		$("#shop4").animate({
			"opacity":0,
		});
	});
	/*banner four部分*//*banner five部分*/
	$(".left").mouseover(function(){
		$(".left_2").animate({
			"opacity":0.3,
		});
	});
	$(".left").mouseleave(function(){
		$(".left_2").animate({
			"opacity":0,
		});
	});
	$(".top").mouseover(function(){
		$(".top_2").animate({
			"opacity":0.3,
		});
	});
	$(".top").mouseleave(function(){
		$(".top_2").animate({
			"opacity":0,
		});
	});
	$(".bottom").mouseover(function(){
		$(".bottom_2").animate({
			"opacity":0.3,
		});
	});
	$(".bottom").mouseleave(function(){
		$(".bottom_2").animate({
			"opacity":0,
		});
	});
	$(".right").mouseover(function(){
		$(".right_6").animate({
			"opacity":0.3,
		});
	});
	$(".right").mouseleave(function(){
		$(".right_6").animate({
			"opacity":0,
		});
	});
	$(".five_top").mouseover(function(){
		$(".ft_1").animate({
			"opacity":0.3,
		});
	});
	$(".five_top").mouseleave(function(){
		$(".ft_1").animate({
			"opacity":0,
		});
	});
	$(".five_bottom").mouseover(function(){
		$(".fb_1").animate({
			"opacity":0.3,
		});
	});
	$(".five_bottom").mouseleave(function(){
		$(".fb_1").animate({
			"opacity":0,
		});
	});
	$(".five_center").mouseover(function(){
		$(".fc_1").animate({
			"opacity":0.3,
		});
	});
	$(".five_center").mouseleave(function(){
		$(".fc_1").animate({
			"opacity":0,
		});
	});
	$(".five_right").mouseover(function(){
		$(".fr_1").animate({
			"opacity":0.3,
		});
	});
	$(".five_right").mouseleave(function(){
		$(".fr_1").animate({
			"opacity":0,
		});
	});
	$(".six_left").mouseover(function(){
		$(".sl_1").animate({
			"opacity":0.3,
		});
	});
	$(".six_left").mouseleave(function(){
		$(".sl_1").animate({
			"opacity":0,
		});
	});
	$(".six_center").mouseover(function(){
		$(".sc_1").animate({
			"opacity":0.3,
		});
	});
	$(".six_center").mouseleave(function(){
		$(".sc_1").animate({
			"opacity":0,
		});
	});
	$(".six_top").mouseover(function(){
		$(".st_1").animate({
			"opacity":0.3,
		});
	});
	$(".six_top").mouseleave(function(){
		$(".st_1").animate({
			"opacity":0,
		});
	});
	$(".six_bottom").mouseover(function(){
		$(".sb_1").animate({
			"opacity":0.3,
		});
	});
	$(".six_bottom").mouseleave(function(){
		$(".sb_1").animate({
			"opacity":0,
		});
	});
	$(".seven_left").mouseover(function(){
		$(".sel_2").animate({
			"opacity":0.3,
		});
	});
	$(".seven_left").mouseleave(function(){
		$(".sel_2").animate({
			"opacity":0,
		});
	});
	$(".seven_center").mouseover(function(){
		$(".sec_2").animate({
			"opacity":0.3,
		});
	});
	$(".seven_center").mouseleave(function(){
		$(".sec_2").animate({
			"opacity":0,
		});
	});
	$(".seven_right").mouseover(function(){
		$(".ser_2").animate({
			"opacity":0.3,
		});
	});
	$(".seven_right").mouseleave(function(){
		$(".ser_2").animate({
			"opacity":0,
		});
	});
	$(".eight").mouseover(function(){
		$(".eight_2").animate({
			"opacity":0.3,
		});
		$(".h").animate({
			"left":"45px",
		},500);
	});
	$(".eight").mouseleave(function(){
		$(".eight_2").animate({
			"opacity":0,
		});
		$(".h").animate({
			"left":"-200px",
		},200);
	});	
	$(".nine_left").mouseover(function(){
		$(".nl_2").animate({
			"opacity":0.3,
		});
	});
	$(".nine_left").mouseleave(function(){
		$(".nl_2").animate({
			"opacity":0,
		});
	});
	$(".nine_right").mouseover(function(){
		$(".nr_2").animate({
			"opacity":0.3,
		});
	});
	$(".nine_right").mouseleave(function(){
		$(".nr_2").animate({
			"opacity":0,
		});
	});
	$(".ten_left").mouseover(function(){
		$(".tl_1").animate({
			"opacity":0.3,
		});
	});
	$(".ten_left").mouseleave(function(){
		$(".tl_1").animate({
			"opacity":0,
		});
	});
	$(".ten_center").mouseover(function(){
		$(".tc_1").animate({
			"opacity":0.3,
		});
	});
	$(".ten_center").mouseleave(function(){
		$(".tc_1").animate({
			"opacity":0,
		});
	});
	$(".ten_top").mouseover(function(){
		$(".tt_1").animate({
			"opacity":0.3,
		});
	});
	$(".ten_top").mouseleave(function(){
		$(".tt_1").animate({
			"opacity":0,
		});
	});
	$(".ten_bottom").mouseover(function(){
		$(".tb_1").animate({
			"opacity":0.3,
		});
	});
	$(".ten_bottom").mouseleave(function(){
		$(".tb_1").animate({
			"opacity":0,
		});
	});
	$(".eleven_top").mouseover(function(){
		$(".et_1").animate({
			"opacity":0.3,
		});
	});
	$(".eleven_top").mouseleave(function(){
		$(".et_1").animate({
			"opacity":0,
		});
	});
	$(".eleven_bottom").mouseover(function(){
		$(".eb_1").animate({
			"opacity":0.3,
		});
	});
	$(".eleven_bottom").mouseleave(function(){
		$(".eb_1").animate({
			"opacity":0,
		});
	});
	$(".eleven_center").mouseover(function(){
		$(".ec_1").animate({
			"opacity":0.3,
		});
	});
	$(".eleven_center").mouseleave(function(){
		$(".ec_1").animate({
			"opacity":0,
		});
	});
	$(".eleven_right").mouseover(function(){
		$(".er_1").animate({
			"opacity":0.3,
		});
	});
	$(".eleven_right").mouseleave(function(){
		$(".er_1").animate({
			"opacity":0,
		});
	});
	$(".twelve_left").mouseover(function(){
		$(".twl_2").animate({
			"opacity":0.3,
		});
	});
	$(".twelve_left").mouseleave(function(){
		$(".twl_2").animate({
			"opacity":0,
		});
	});
	$(".twelve_right").mouseover(function(){
		$(".twr_2").animate({
			"opacity":0.3,
		});
	});
	$(".twelve_right").mouseleave(function(){
		$(".twr_2").animate({
			"opacity":0,
		});
	});
	/*footer*/
	$(".wx").mouseover(function(){
		$(".href1").css({
			"display":"block",
		});
	});
	$(".wx").mouseleave(function(){
		$(".href1").css({
			"display":"none",
		});
	});
	$(".wb").mouseover(function(){
		$(".href2").css({
			"display":"block",
		});
	});
	$(".wb").mouseleave(function(){
		$(".href2").css({
			"display":"none",
		});
	});
	$(".href1").mouseover(function(){
		$(".href1").css({
			"display":"block",
		});
	});
	$(".href1").mouseleave(function(){
		$(".href1").css({
			"display":"none",
		});
	});
	$(".href2").mouseover(function(){
		$(".href2").css({
			"display":"block",
		});
	});
	$(".href2").mouseleave(function(){
		$(".href2").css({
			"display":"none",
		});
	});
	$(".tool").mouseover(function(){
		$(".chat").css({
			"display":"block",
		});
	});
	$(".tool").mouseleave(function(){
		$(".chat").css({
			"display":"none",
		});
	});
	$(".tool1").mouseover(function(){
		$(".wxwx").css({
			"display":"block",
		});
		$(".tool5").css({
			"display":"block",
		});
	});
	$(".tool1").mouseleave(function(){
		$(".wxwx").css({
			"display":"none",
		});
		$(".tool5").css({
			"display":"none",
		});
	});
	$(".tool5").mouseover(function(){
		$(".tool5").css({
			"display":"block",
		});
		$(".wxwx").css({
			"display":"block",
		});
	});
	$(".tool5").mouseleave(function(){
		$(".tool5").css({
			"display":"none",
		});
		$(".wxwx").css({
			"display":"none",
		});
	});
	$(".tool2").mouseover(function(){
		$(".app").css({
			"display":"block",
		});
		$(".tool6").css({
			"display":"block",
		});
	});
	$(".tool2").mouseleave(function(){
		$(".app").css({
			"display":"none",
		});
		$(".tool6").css({
			"display":"none",
		});
	});
	$(".tool6").mouseover(function(){
		$(".tool6").css({
			"display":"block",
		});
		$(".app").css({
			"display":"block",
		});
	});
	$(".tool6").mouseleave(function(){
		$(".tool6").css({
			"display":"none",
		});
		$(".app").css({
			"display":"none",
		});
	});
	$(".tool3").mouseleave(function(){
		$(".back").css({
			"display":"none",
		});
	});
	$(".tool3").mouseover(function(){
		$(".back").css({
			"display":"block",
		});
	});
	/*main部分*/
	$('.clr').animate({"left":"-156px"},300,function(){
		$(".clr").css("left",0).find("li").eq(0).appendTo($(this));
	});
	$('.next').click(function(){
		$('.clr').animate({"left":"-156px"},300,function(){
			$(".clr").css("left",0).find("li").eq(0).appendTo($(this));	
		});
	});
	$('.prev').click(function(){
		$(".clr").find("li").eq(13).insertBefore($(".clr").find("li").eq(0));
		$(".clr").css("left","-156px");
		$('.clr').animate({"left":"0px"},300);
	});
});


	
	
